# Site settings
title: JIM Blog
SEOTitle: JIM的博客 | JIM Blog
header-img: img/blue-tiger.jpg
email: xingjian_zhang@sjtu.edu.cn
description: "Engineers Change The World!"
keyword: "University, JIM的博客, SJTU, Joint Institute"
url: "http://marco-jimmy.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Marco-Jimmy/Marco-Jimmy.github.io.git" # you code repository

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "Engineers change the world!"
sidebar-avatar: /img/avatar.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
# weibo_username:     qiubaiying
# zhihu_username:     高速怨曲
github_username: Marco-Jimmy
# facebook_username:  baiying.qiu.7
# jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM # use Github Flavored Markdown !important

# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
    enable: true #是否开启Gitalk评论
    clientID: 79d69c624ec99fa24b59 #生成的clientID
    clientSecret: 8a99af009452e6bd4432d3120b5d823278603bc0 #生成的clientSecret
    repo: Marco-Jimmy.github.io #仓库名称
    owner: Marco-Jimmy #github用户名
    admin: Marco-Jimmy
    distractionFreeMode: true #是否启用类似FB的阴影遮罩

# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Featured Tags
featured-tags: true # 是否使用首页标签
featured-condition-size: 0 # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends:
    [
        { title: "UM-SJTU Joint Institute", href: "http://umji.sjtu.edu.cn/" },
        { title: "Github", href: "https://github.com/Marco-Jimmy/" },
        { title: "CSDN", href: "https://blog.csdn.net/weixin_44009599" },
        { title: "Digital Clock", href:"https://marco-jimmy.github.io/digital-clock/"},
        { title: "Simple Game", href:"https://marco-jimmy.github.io/rock_paper_scissors/"}
    ]
